#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,mem=2gb,walltime=1:00:00
#PBS -M mschumm@uchicago.edu
#PBS -m abe
#PBS -N mussels-seastars-abm
#PBS -j oe
#PBS -t 1

# Must increase heapsize in netlogo-headless.sh (e.g., -Xmx2048m)
/home/t.cri.mschumm/NetLogo-6.0.4/netlogo-headless.sh \
    --model ~/mussels-seastars-abm.nlogo3d --3D \
    --setup-file mussels-experiments.xml --experiment experiment-$PBS_ARRAYID \
    --table ~/output/output-$PBS_ARRAYID.csv --threads 1
